### ISSUE TITLE
classwork04

### ISSUE THREAD

**Issue by GolAnd071** [RogMin/MIPT-CODING#1]
По заданию на numpy: 6 неправильно посчитан (не range(-10, 1, 1), а range(-9, 2, 1), чтобы значения были от -9 до 1 включительно); в 9 не нужен floor, там получается 0.

**Comment by GolAnd071** [comment]
По заданию на matplotlib: хорошо бы было сделать по графику на каждый пункт; у 1 и 2 графиков в задании указаны другой шаг и диапазон значений x; нет графиков 3-6; в 7 пункте неправильный шаг и диапазон; в 8 пункте не тот график.

**Comment by GolAnd071** [comment]
По заданию Data Analysis: погрешности гораздо больше самих значений; наверное, так быть не должно.

**Comment by RogMin** [comment]
Исправил
